#!/usr/bin/env ruby

lib = File.expand_path("../lib", __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

# Avoid mixing error output into redirect value
$stderr.reopen("depdump-error.log", "w")

require "depdump"
require "optparse"

options = ARGV.getopts("o:")

Depdump.configure do |c|
  c.output = File.open(options["o"], "w") if options["o"]
end

files = ARGV.empty? ? ["."] : ARGV
Depdump.new.run(files)
