#!/usr/bin/env ruby

lib = File.expand_path("../lib", __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

# Avoid mixing error output into redirect value
$stderr.reopen("depdump-error.log", "w")

require "depdump"

files = ARGV.empty? ? ["."] : ARGV
puts Depdump.new.run(files)
